### ISSUE TITLE
Performance comparison vs. the benchmark

### ISSUE THREAD

**Issue by xylimeng** [nasyring/GSOC-BayesBD#2]
Could we have some comparison in terms of the speed gain by doing the cpp, compared to the original package? Both functions should produce same results when the random number generators are controlled.

**Comment by nasyring** [comment]
I have done some speed comparisons, which you can run in the updated version of the code.  I am unsure what speed increase we should expect to see because I am not very familiar with C++ versus R in general, but, so far, there is a substantial speed increase.  The C++ codes run in about 1/3 the time of the R code.  I expect some further efficiencies could be gained.

**Comment by nasyring** [comment]
By the way, the tests are for a 100 x 100 binary image, 5000 posterior samples and 1000 burn in.

**Comment by xylimeng** [comment]
I thought I commented here but glad to see you commit the normal noise situation. Usually c++ code improves the efficiency by 5-20 times and sometimes even more. I think to cut the time to 1/3 is already great. I saw you were using "cppFunction", and in your benchmark test, the 'system' time for c++ code is quite significant. An easy improvement could be: use "sourceRcpp" to compile the c++ code and then run the function. In this case, part of the 'system' time will be taken in the sourceRcpp step. I'm not sure how much it helps but think it worth a try.

**Comment by nasyring** [comment]
I have tried using sourceRcpp as you mentioned, but I did not find any performance gains over using cppFunction.  Perhaps more surprising, my c++ code for the Gaussian-noised images is actually much slower than R -- it takes about twice as long to run.  So far, I know that the eigenfunction computations are slower in my c++ code than in R, but this does not make much difference, and is only really noticeable before the sampling loop.  I am not sure what part within the sampling loop is causing the slowdown.  It think that the slice sampling of the 'a' parameter is ok, because this is unchanged from the binary case.  I have made considerable use of the RcppArmadillo library for matrix and vector calculations, but in my tests it doesn't seem to be any faster than ordinary R code.  So, my guess is that the MCMC sampling I have for the basis function coefficients is slower in c++ than in R.  This function contains only one loop, which I have tried replacing with an Rcpp Sugar ifelse statement, but that did not speed things up at all.  On a related note, I have not used the slice sampling for the coefficients because I could not get it to work yet.  So, that potentially may be a way to speed up the code.

**Comment by xylimeng** [comment]
For the speed issue, some profiling is needed. 
- There are many tools to profile R and/or compiled code (for example, a quick google search gives, http://stackoverflow.com/questions/13224322/profiling-rcpp-code-on-os-x, see the solution mentioned there). 
- Alternatively, in the MCMC loop, you can do a dummy update (don't really draw samples but keep using some fixed values or just previous samples) for one parameter once a time, then check how the running time changes. We don't have many parameters so this may be a quick check; while the long-term solution is a formal code profiling. Since the code works as expected for binary noise, and the update of coefficients is a major change for the normal case, you may consider to try a dummy update for the coefficients first. 

Slice sampling is applicable here regardless of noise types. Depending on the resolution to the point above, let's come back to this later on.

**Comment by nasyring** [comment]
Sorry that this has taken awhile to get resolved, but I think I am almost ready to post the (essentially) finished code for the binary and normal images.  

I posted a small update today to highlight the major change, but the full update will come tomorrow, 7/16.  

I have found that the best way to write fast c++ code is to avoid function calls whenever possible.  To this point, I have been doing MCMC updates to model parameters in a loop by calling a function to do slice (or MH) sampling.  This actually is very bad.  The problem is that every time the function is called, variables inside the function are created and space is filled in memory.  If the function is in a loop, as the MCMC updates are, this is a lot of repeated memory allocation.  So, I have begun replacing function calls with inline code.  The advantage is that variables are only created once, and then values are changed as the sampling is done.  This speeds up the code considerably.  The drawback is that the code becomes somewhat less readable, but I will comment it thoroughly, and then, ultimately, no user will ever need to see the code from within R.  

I have been working on a laptop away from home for the past week, but I will be back to my fast computer tomorrow so that I can do a proper time comparison.

**Comment by nasyring** [comment]
I have sped up the code considerably.  The binary example I have done runs in about 1 minute, close to four times faster than the R code.  The Gaussian example I have done runs in about 5 minutes using slcie sampling, which is about 9 times faster than the R code.  Using Metropolis Hastings sampling for the eigenfunction coefficients, the same example runs in under thirty seconds, about 3 times faster than the R code.  The reason for the huge time difference between the sampling methods boils down to the number of likelihood evaluations performed.  Slice sampling guarantees unique samples, but costs sometimes as many as 40 likelihood evaluations per sample in the examples I have done.  Metropolis Hastings sampling of course only requires two likelihood calculations for each sample.  

Next, I will finish the other examples from the paper and run the full simulation study, adding in the credible regions to test the performance more thoroughly both for accuracy and speed.  I will also see if the slice sampling gets better results than MH sampling in any of the Gaussian examples.  I could potentially add MH sampling to the binary examples, but the code is already fairly fast and the likelihood calculations are less intensive in those problems, so I wouldn't expect as much of a gain.

**Comment by xylimeng** [comment]
That's super nice. Great job! 
An alternative approach to resolute the repeated memory allocation issue is to use "pointers" so that the same variables can be updated by calling a function without creating their duplicates. We of course should keep with your current coding flow - inline codes with comments, but in the future for some other projects, this may be a useful note. 
When commenting the code, it'll be useful to include which part of the code needs to be changed if we change the noise types (say, if we have Poisson noised observations). 
Looking foward to a thorough testing!
